# -*- coding: utf-8 -*-
"""questao3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nIwDWAOhbO1Ma2HHHStLUKP445t5lnpl
"""

#FELIPE RODRIGUES DE SOUSA - 202504000
#QUESTÃO 3

import numpy as np # Importa a biblioteca NumPy.
import pandas as pd # Importa a biblioteca Pandas.

np.random.seed(42) # Define uma semente para reprodutibilidade dos resultados.
temperaturas = np.random.normal(loc=26, scale=5, size=30) # Gera 30 temperaturas aleatórias com média 26 e desvio padrão 5.
temperaturas = np.round(temperaturas, 1) # Arredonda as temperaturas para uma casa decimal.
print(f"Temperaturas: {temperaturas}") # Exibe as temperaturas geradas.

media = np.mean(temperaturas) # Calcula a média das temperaturas.
mediana = np.median(temperaturas) # Calcula a mediana das temperaturas.
desvio_padrao = np.std(temperaturas) # Calcula o desvio padrão das temperaturas.
variacao_termica = np.max(temperaturas) - np.min(temperaturas) # Calcula a variação térmica.

print("ESTATÍSTICAS:") # Imprime cabeçalho de estatísticas.
print(f"Média: {media:.2f}°C") # Exibe a média.
print(f"Mediana: {mediana:.2f}°C") # Exibe a mediana.
print(f"Desvio padrão: {desvio_padrao:.2f}°C") # Exibe o desvio padrão.
print(f"Variação térmica: {variacao_termica:.2f}°C") # Exibe a variação térmica.

df = pd.DataFrame({ # Cria um DataFrame do Pandas.
    'Dia': np.arange(1, 31), # Coluna para o dia do mês.
    'Temperatura (°C)': temperaturas # Coluna para as temperaturas.
})

df['Diferença para a média'] = np.round(df['Temperatura (°C)'] - media, 2) # Calcula a diferença de cada temperatura em relação à média.

def classificar(temp): # Define função para classificar a temperatura.
    if temp < 18:
        return "Frio"
    elif temp <= 25:
        return "Agradável"
    else:
        return "Quente"

df['Classificação térmica'] = df['Temperatura (°C)'].apply(classificar) # Aplica a classificação térmica a cada temperatura.

print("\nCLASSIFICAÇÕES:") # Imprime cabeçalho de classificações.
print(df['Classificação térmica'].value_counts()) # Conta a ocorrência de cada classificação.

mais_quentes = df.sort_values(by='Temperatura (°C)', ascending=False).head(5) # Seleciona os 5 dias mais quentes.
mais_frios = df.sort_values(by='Temperatura (°C)').head(5) # Seleciona os 5 dias mais frios.
quentes_frios = pd.concat([mais_quentes, mais_frios]) # Concatena os DataFrames dos dias quentes e frios.

def posicao_relacao_media(x): # Define função para a posição em relação à média.
    if x > 0:
        return "Acima da média"
    elif x < 0:
        return "Abaixo da média"
    else:
        return "Exatamente na média"

quentes_frios['Comparação com média'] = quentes_frios['Diferença para a média'].apply(posicao_relacao_media) # Aplica a comparação com a média.

print("\5 DIAS MAIS QUENTES:") # Imprime cabeçalho.
print(mais_quentes[['Dia', 'Temperatura (°C)', 'Classificação térmica', 'Diferença para a média']]) # Exibe os 5 dias mais quentes.

print("\n5 DIAS MAIS FRIOS:") # Imprime cabeçalho.
print(mais_frios[['Dia', 'Temperatura (°C)', 'Classificação térmica', 'Diferença para a média']]) # Exibe os 5 dias mais frios.

print("\nANÁLISE DOS 10 EXTREMOS:") # Imprime cabeçalho.
print(quentes_frios[['Dia', 'Temperatura (°C)', 'Classificação térmica', 'Diferença para a média', 'Comparação com média']]) # Exibe a análise dos extremos.

frio_acima_media = ((df['Classificação térmica'] == 'Frio') & (df['Diferença para a média'] > 0)).any() # Verifica se houve dia "Frio" acima da média.
quente_abaixo_media = ((df['Classificação térmica'] == 'Quente') & (df['Diferença para a média'] < 0)).any() # Verifica se houve dia "Quente" abaixo da média.

print("\nVERIFICAÇÕES:") # Imprime cabeçalho.
print("Houve dia 'Frio' acima da média?", "Sim" if frio_acima_media else "Não") # Exibe o resultado da verificação.
print("Houve dia 'Quente' abaixo da média?", "Sim" if quente_abaixo_media else "Não") # Exibe o resultado da verificação.

import numpy as np
import pandas as pd

np.random.seed(42)
temperaturas = np.random.normal(loc=26, scale=5, size=30)
temperaturas = np.round(temperaturas, 1)

media = np.mean(temperaturas)
mediana = np.median(temperaturas)
desvio_padrao = np.std(temperaturas)
variacao_termica = np.max(temperaturas) - np.min(temperaturas)

print("ESTATÍSTICAS:")
print(f"Média: {media:.2f}°C")
print(f"Mediana: {mediana:.2f}°C")
print(f"Desvio padrão: {desvio_padrao:.2f}°C")
print(f"Variação térmica: {variacao_termica:.2f}°C")

df = pd.DataFrame({
    'Dia': np.arange(1, 31),
    'Temperatura (°C)': temperaturas
})

df['Diferença para a média'] = np.round(df['Temperatura (°C)'] - media, 2)

def classificar(temp):
    if temp < 18:
        return "Frio"
    elif temp <= 25:
        return "Agradável"
    else:
        return "Quente"

df['Classificação térmica'] = df['Temperatura (°C)'].apply(classificar)
import numpy as np
import pandas as pd

np.random.seed(42)
temperaturas = np.random.normal(loc=26, scale=5, size=30)
temperaturas = np.round(temperaturas, 1)

media = np.mean(temperaturas)
mediana = np.median(temperaturas)
desvio_padrao = np.std(temperaturas)
variacao_termica = np.max(temperaturas) - np.min(temperaturas)

print("ESTATÍSTICAS:")
print(f"Média: {media:.2f}°C")
print(f"Mediana: {mediana:.2f}°C")
print(f"Desvio padrão: {desvio_padrao:.2f}°C")
print(f"Variação térmica: {variacao_termica:.2f}°C")

df = pd.DataFrame({
    'Dia': np.arange(1, 31),
    'Temperatura (°C)': temperaturas
})

df['Diferença para a média'] = np.round(df['Temperatura (°C)'] - media, 2)

def classificar(temp):
    if temp < 18:
        return "Frio"
    elif temp <= 25:
        return "Agradável"
    else:
        return "Quente"

df['Classificação térmica'] = df['Temperatura (°C)'].apply(classificar)

print("\nCLASSIFICAÇÕES:")
print(df['Classificação térmica'].value_counts())

mais_quentes = df.sort_values(by='Temperatura (°C)', ascending=False).head(5)
mais_frios = df.sort_values(by='Temperatura (°C)').head(5)
quentes_frios = pd.concat([mais_quentes, mais_frios])

def posicao_relacao_media(x):
    if x > 0:
        return "Acima da média"
    elif x < 0:
        return "Abaixo da média"
    else:
        return "Exatamente na média"

quentes_frios['Comparação com média'] = quentes_frios['Diferença para a média'].apply(posicao_relacao_media)

print("\n5 DIAS MAIS QUENTES:")
print(mais_quentes[['Dia', 'Temperatura (°C)', 'Classificação térmica', 'Diferença para a média']])

print("\n5 DIAS MAIS FRIOS:")
print(mais_frios[['Dia', 'Temperatura (°C)', 'Classificação térmica', 'Diferença para a média']])

print("\nANÁLISE DOS 10 EXTREMOS:")
print(quentes_frios[['Dia', 'Temperatura (°C)', 'Classificação térmica', 'Diferença para a média', 'Comparação com média']])

frio_acima_media = ((df['Classificação térmica'] == 'Frio') & (df['Diferença para a média'] > 0)).any()
quente_abaixo_media = ((df['Classificação térmica'] == 'Quente') & (df['Diferença para a média'] < 0)).any()

print("\nVERIFICAÇÕES:")
print("Houve dia 'Frio' acima da média?", "Sim" if frio_acima_media else "Não")
print("Houve dia 'Quente' abaixo da média?", "Sim" if quente_abaixo_media else "Não")