# -*- coding: utf-8 -*-
"""questao1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L18YGoALzvLjVSQZLIDfPoC8NO86Iexc
"""

#FELIPE RODRIGUES DE SOUSA - 202504000
#QUESTÃO 1

kW = float(input("Digite a potência do aparelho em kW (ex: 1.2): ")) # Solicita potência em kW.
h_dia = int(input("Digite o tempo médio de uso diário em horas (ex: 4): ")) # Solicita uso diário em horas.

def calcular_consumo_mensal(pot, horas): # Define função para consumo mensal.
    consumo_mensal = pot * horas * 30 # Calcula consumo do mês.
    return consumo_mensal # Retorna o consumo.

erros = [] # Lista para erros de validação.
if kW <= 0: # Valida potência.
    erros.append("Valor kW inválido.")
if h_dia <= 0 or h_dia > 24: # Valida horas de uso.
    erros.append("Valor horas inválido.")

if erros: # Se há erros.
    for erro in erros: # Exibe cada erro.
        print(erro)
else: # Se não há erros.
    print("RESULTADOS:") # Imprime cabeçalho.
    print(f"Potência do aparelho: {kW}kW")
    print(f"Tempo médio de uso diário: {h_dia}h")
    print(f"Consumo mensal estimado: {calcular_consumo_mensal(kW, h_dia)}kWh") # Chama a função e imprime o consumo.