# -*- coding: utf-8 -*-
"""questao4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DTh3mUd_EFFYHpZeV2q70HXgmG2gz3fP
"""

#FELIPE RODRIGUES DE SOUSA - 202504000
#QUESTÃO 4

import pandas as pd
import numpy as np
import random

LINHAS = 20
COLUNAS = 10
tabuleiro = pd.DataFrame(0, index=range(LINHAS), columns=range(COLUNAS)) # Cria o tabuleiro do jogo (DataFrame).

def mostrar_tabuleiro():
    print(tabuleiro.replace({0: '.', 1: '■'})) # Exibe o tabuleiro com representação visual.

# Formas dos blocos
blocos = {
    'I': [[1, 1, 1, 1]],
    'O': [[1, 1], [1, 1]],
    'T': [[0, 1, 0], [1, 1, 1]],
    'L': [[1, 0], [1, 0], [1, 1]],
    'J': [[0, 1], [0, 1], [1, 1]],
    'S': [[0, 1, 1], [1, 1, 0]],
    'Z': [[1, 1, 0], [0, 1, 1]]
}

def gerar_bloco():
    nome = random.choice(list(blocos.keys())) # Escolhe um bloco aleatoriamente.
    return nome, np.array(blocos[nome]) # Retorna o nome e a matriz do bloco.

def pode_colocar_bloco(bloco, linha, coluna): # Verifica se o bloco pode ser posicionado.
    l_b, c_b = bloco.shape
    if linha + l_b > LINHAS or coluna < 0 or coluna + c_b > COLUNAS: # Checa limites do tabuleiro.
        return False
    for i in range(l_b):
        for j in range(c_b):
            if bloco[i][j] == 1 and tabuleiro.iat[linha+i, coluna+j] == 1: # Verifica colisões com blocos existentes.
                return False
    return True

def posicionar_bloco(bloco, coluna): # Posiciona o bloco no tabuleiro.
    l_b, c_b = bloco.shape
    for linha in range(LINHAS - l_b + 1): # Procura a primeira linha válida para o bloco cair.
        if not pode_colocar_bloco(bloco, linha + 1, coluna): # Se a próxima posição não é válida, ele se encaixa na atual.
            for i in range(l_b):
                for j in range(c_b):
                    if bloco[i][j] == 1:
                        tabuleiro.iat[linha + i, coluna + j] = 1 # Define a posição do bloco no tabuleiro.
            return True
    return False

def verificar_linhas(): # Verifica e remove linhas completas.
    global tabuleiro
    linhas_removidas = 0
    for i in range(LINHAS):
        if all(tabuleiro.iloc[i] == 1): # Se a linha estiver completa.
            linhas_removidas += 1
            tabuleiro = pd.concat([ # Remove a linha e adiciona uma nova vazia no topo.
                pd.DataFrame([[0]*COLUNAS], columns=tabuleiro.columns),
                tabuleiro.drop(i).reset_index(drop=True)
            ], ignore_index=True)
    if linhas_removidas > 0:
        print(f"{linhas_removidas} linha(s) removida(s)!")

jogo_ativo = True
mostrar_tabuleiro()

while jogo_ativo: # Loop principal do jogo.
    nome, bloco = gerar_bloco() # Gera um novo bloco.
    coluna = 3 # Coluna inicial do bloco.
    print(f"\nBloco sorteado: {nome}")

    while True: # Loop para o movimento do bloco atual.
        print("\nBloco atual:")
        print(pd.DataFrame(bloco).replace({0: '.', 1: '■'})) # Exibe o bloco atual.
        print(f"Coluna atual: {coluna}")

        entrada = input("Comandos: '<' | '>' | 'r' | 'c' | 'sair': ").strip().lower() # Solicita comando do usuário.

        if entrada == 'sair': # Encerra o jogo.
            print("Jogo encerrado.")
            jogo_ativo = False
            break
        elif entrada == '<': # Move o bloco para a esquerda.
            if coluna > 0 and coluna - 1 + bloco.shape[1] <= COLUNAS: # Valida movimento.
                coluna -= 1
            else:
                print("Movimento inválido.")
        elif entrada == '>': # Move o bloco para a direita.
            if coluna + 1 + bloco.shape[1] <= COLUNAS: # Valida movimento.
                coluna += 1
            else:
                print("Movimento inválido.")
        elif entrada == 'r': # Rotaciona o bloco.
            novo_bloco = np.rot90(bloco, -1) # Gira o bloco 90 graus no sentido horário.
            if coluna + novo_bloco.shape[1] <= COLUNAS: # Valida rotação.
                bloco = novo_bloco
            else:
                print("Rotação inválida.")
        elif entrada == 'c': # Confirma a queda do bloco.
            if pode_colocar_bloco(bloco, 0, coluna): # Verifica se pode iniciar a queda.
                if not posicionar_bloco(bloco, coluna): # Posiciona o bloco e verifica se foi possível.
                    print("Não foi possível posicionar o bloco. Fim de jogo.")
                    jogo_ativo = False
                    break
                break # Sai do loop do bloco, passa para o próximo.
            else:
                print("Posição inválida!")
        else:
            print("Comando inválido.")

    if jogo_ativo: # Se o jogo ainda está ativo.
        verificar_linhas() # Verifica e remove linhas.
        mostrar_tabuleiro() # Exibe o tabuleiro atualizado.