# -*- coding: utf-8 -*-
"""questao2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FWR7KsqV4FQuZ5reK1avmD1nNf2AutsV
"""

#FELIPE RODRIGUES DE SOUSA - 202504000
#QUESTÃO 2

print("METAS DE GASTOS MENSAIS POR CATEGORIA:")
metas = {} # Dicionário para armazenar as metas por categoria.
while True:
    categoria = input("Digite o nome da categoria (ou 'fim' para encerrar): ")
    if categoria.lower() == 'fim':
        break
    valor = float(input(f"Digite a meta de gasto para '{categoria}': R$ "))
    metas[categoria] = valor

n_lancamentos = int(input("Digite a quantidade de lançamentos que deseja registrar: "))

despesas = [] # Lista para armazenar todos os lançamentos de despesa.
for i in range(n_lancamentos):
    print(f"\nLançamento {i+1}:")
    descricao = input("Descrição da despesa: ")
    valor = float(input("Valor da despesa (R$): "))
    categoria = input("Categoria: ")

    despesas.append({
        'descricao': descricao,
        'valor': valor,
        'categoria': categoria
    })

total = 0 # Acumulador do total de despesas.
gasto_categoria = {} # Dicionário para somar gastos por categoria.

for despesa in despesas:
    valor = despesa['valor']
    categoria = despesa['categoria']
    total += valor

    if categoria in gasto_categoria:
        gasto_categoria[categoria] += valor
    else:
        gasto_categoria[categoria] = valor

media_categoria = {} # Dicionário para armazenar a média de gastos por categoria.
for categoria, total_gasto in gasto_categoria.items():
    quantidade = sum(1 for d in despesas if d['categoria'] == categoria) # Conta quantas despesas existem em cada categoria.
    media = total_gasto / quantidade if quantidade > 0 else 0 # Calcula a média, evitando divisão por zero.
    media_categoria[categoria] = media

categoria_maior_valor = max(gasto_categoria, key=gasto_categoria.get) # Encontra a categoria com o maior valor gasto.

print("\nRELATÓRIO:")
print(f"Total de despesas no mês: R$ {total:.2f}")

print("\nGastos por categoria:")
for categoria, total_gasto in gasto_categoria.items():
    print(f"{categoria}: R$ {total_gasto:.2f}")

print("\nMédia de gastos por categoria:")
for categoria, media in media_categoria.items():
    print(f"{categoria}: R$ {media:.2f}")

print(f"\nCategoria com maior gasto: {categoria_maior_valor} (R$ {gasto_categoria[categoria_maior_valor]:.2f})")

print("\nComparativo com metas:")
for categoria, meta in metas.items():
    gasto = gasto_categoria.get(categoria, 0) # Retorna o gasto da categoria ou 0 se a categoria não tiver gastos.
    diferenca = gasto - meta
    status = "ACIMA" if diferenca > 0 else "DENTRO" # Define o status: "ACIMA" ou "DENTRO" da meta.
    print(f"{categoria}: Gasto R$ {gasto:.2f}, Meta R$ {meta:.2f} => {status} da meta (diferença de R$ {diferenca:.2f})")